nlnwa/veidemann-dashboard

- src/app/app.component.html
- src/app/app.module.ts
- src/app/commons/models/label.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.html
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-list/crawlhostgroupconfig-list.component.html
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-list/crawlhostgroupconfig-list.component.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-list/crawlhostgroupconfig-list.component.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig.service.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig.service.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig.ts
- src/app/configurations/crawlhostgroupconfig/index.ts
- src/app/entities/entity-details/entity-details.component.html
- src/app/entities/entity-details/entity-details.component.ts
- src/app/routes.ts
- src/app/seeds/seed-details/seed-details.component.ts
Added GUI for configuring crawl host groups
> Crawlhostgroupconfig

- src/app/configurations/crawljobs/crawljob-details/crawljob-details.component.html
- src/app/configurations/crawljobs/crawljob-details/crawljob-details.component.ts
- src/app/configurations/crawljobs/crawljob-list/crawljob-list.component.ts
Updated crawljob form with the missing field _disabled_, and made it configurable through toggle switch. 
Fix for creating and deleting a crawljob.
> Add disabled input to crawljob form

- package.json
- src/app/commons/datetime.ts
- src/app/configurations/schedule/schedule-details/schedule-details.component.css
- src/app/configurations/schedule/schedule-details/schedule-details.component.html
- src/app/configurations/schedule/schedule-details/schedule-details.component.ts
- yarn.lock
Add regex validation to inputs. 
Add moment.js to handle dates in utc
> Schedule input validation

- src/app/commons/custom-error.ts
Custom errors should inherit from this base custom error
> Implement base custom error

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/configurations/crawlconfig/crawlconfig-details/crawlconfig-details.component.html
- src/app/configurations/crawlconfig/crawlconfig-details/crawlconfig-details.component.ts
- src/app/configurations/crawlconfig/crawlconfig-list/crawlconfig-list.component.html
- src/app/configurations/crawlconfig/crawlconfig-list/crawlconfig-list.component.ts
- src/app/configurations/crawlconfig/crawlconfig-page.component.ts
- src/app/configurations/crawlconfig/index.ts
Make container page and use base list
> Refactor crawlconfigs

- src/app/app.component.spec.ts
- src/app/configurations/browserscript/browserscript-details/browserscript-details.component.spec.ts
- src/app/configurations/browserscript/browserscript-details/browserscript-details.component.ts
- src/app/configurations/browserscript/browserscript-list/browserscript-list.component.spec.ts
- src/app/configurations/browserscript/browserscript.service.spec.ts
- src/app/configurations/crawlconfig/crawlconfig-details/crawlconfig-details.component.spec.ts
- src/app/configurations/crawlconfig/crawlconfig-list/crawlconfig-list.component.spec.ts
- src/app/configurations/crawlconfig/crawlconfig.service.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-list/crawlhostgroupconfig-list.component.spec.ts
- src/app/configurations/crawljobs/crawljob-details/crawljob-details.component.spec.ts
- src/app/configurations/crawljobs/crawljob-list/crawljob-list.component.spec.ts
- src/app/configurations/crawljobs/crawljob.service.spec.ts
- src/app/configurations/logs/log.service.spec.ts
- src/app/configurations/logs/logconfig/loglevel.component.spec.ts
- src/app/documentation/documentation.component.spec.ts
- src/app/entities/entity-details/entity-details.component.spec.ts
- src/app/entities/entity.service.spec.ts
- src/app/labels/labels.component.spec.ts
- src/app/seeds/seeds.service.spec.ts
- src/app/snack-bar-service/snack-bar.service.spec.ts
- src/app/statistics/statistics.component.spec.ts
- src/test.ts
- Added tests for browserscript-details
- Edited CLI generated tests with xdescribe to skip unfinished tests
> Tests for browserscript-details

- src/app/configurations/schedule/schedule-details/schedule-details.component.spec.ts
- src/app/configurations/schedule/schedule-details/schedule-details.component.ts
- src/app/configurations/schedule/schedule-list/schedule-list.component.spec.ts
- src/app/configurations/schedule/schedule.service.spec.ts
- src/test.ts
Add tests for schedule-details.component. Add xdescribe to skip unfinished CLI generated tests.…ished CLI generated tests.
> Add tests for schedule-details.component.

- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-list/crawlhostgroupconfig-list.component.spec.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig.service.spec.ts
Add tests for crawlhostgroupconfig-details.component. 
Add xdescribe to unfinished tests for list and service
> Add tests for crawlhostgroupconfig-details.component

- Dockerfile
- nginx/default.conf
- src/app/auth/auth.service.ts
- src/app/auth/token.interceptor.ts
- src/app/configurations/browserconfig/browserconfig.service.ts
- src/app/configurations/browserscript/browserscript.service.ts
- src/app/configurations/crawlconfig/crawlconfig.service.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig.service.ts
- src/app/configurations/crawljobs/crawljob.service.ts
- src/app/configurations/logs/log.service.ts
- src/app/configurations/politenessconfig/politenessconfig.service.ts
- src/app/configurations/schedule/schedule.service.ts
- src/app/dialog/dialog.component.ts
- src/app/entities/entity.service.ts
- src/app/seeds/seeds.service.ts
- src/assets/auth_config.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
Also fix the problem with the error dialog disappearing quickly when multiple errors, and filter the http interceptor to only add bearer token when talking to api
> Nginx, dockerfile reconfiguration

- src/app/seeds/seed-details/seed-details.component.ts
Crawljob is not required to create a seed
> Relax validation on seed creation

- src/app/configurations/entities/entity-details/entity-details.component.css
- src/app/configurations/rolemapping/rolemapping-details/rolemapping-details.component.html
- src/app/configurations/seeds/seed-details/seed-details.component.css
- src/app/configurations/seeds/seed-details/seed-details.component.html
- Fix flexLayout for rolemapping, to avoid chrome bug
- Fix alignment issues in search
> Flex alignment

- package.json
- src/app/commons/datetime/datetime.ts
- src/app/commons/meta/meta.component.html
- src/app/commons/meta/meta.component.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.html
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.ts
- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-ipvalidation.ts
- src/app/configurations/crawljobs/crawljob-details/crawljob-details.component.ts
- yarn.lock
- Validate ipv4 and ipv6 addresses
- Simple check on from-to ip range
> Ipv4/v6 validation CrawlHostGroupConfig

- src/app/configurations/crawlhostgroupconfig/crawlhostgroupconfig-details/crawlhostgroupconfig-details.component.html
- src/app/configurations/entities/entity-details/entity-details.component.html
- src/app/configurations/schedule/schedule-details/schedule-details.component.html
- src/app/configurations/seeds/seed-details/seed-details.component.html
Add spacing between columns in entity/seed
Wider input field in crawlhostgroupconfig to fit IPv6 addresses
> fix: Small layout changes

- angular.json
- src/app/app.component.html
- src/app/app.component.ts
feat: add button for accessing dashboard docs
> fix: typo in baseHref

- src/api/index.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/modules/commons/models/app-config.model.ts
- src/modules/commons/models/configs/loglevel.model.ts
- src/modules/configurations/configurations.module.ts
- src/modules/configurations/containers/logconfig/loglevel.component.html
- src/modules/configurations/containers/logconfig/loglevel.component.ts
- src/modules/configurations/routing/configurations-routing.module.ts
- src/modules/configurations/services/index.ts
- src/modules/configurations/services/log.resolver.service.ts
- src/modules/configurations/services/log.service.ts
- src/modules/core/services/app.initializer.service.ts
- Remove traces of old api gateway
> Use grpc-web in logLevel component

- src/modules/commons/components/seed-meta/seed-meta.component.html
- src/modules/commons/components/seed-meta/seed-meta.component.ts
- src/modules/commons/validator/existing-url-validation.ts
- src/modules/commons/validator/patterns.ts
- Show progress bar when validating URL's
- Check URL pattern one by one
> improve url validation

- src/modules/configurations/services/label.service.ts
- src/modules/event/component/event-new-seed/event-new-seed.component.spec.ts
- src/modules/event/containers/event-search/event-search.component.spec.ts
- src/modules/event/containers/event-search/event-search.component.ts
- src/modules/event/event.module.ts
- src/modules/event/routing/event-routing.module.ts
- src/modules/event/services/options.resolver.service.ts
- Create own OptionsResolver for use with events
- Workaround for nonworking  autocomplete on labels
> Use seperate optionsresolver for event component

- src/modules/core/services/api/report-api.service.ts
- src/modules/report/components/crawl-execution-status-list/crawl-execution-status-list.component.html
- src/modules/report/components/crawl-execution-status-list/crawl-execution-status-list.component.ts
Was sortable on createdTime but API semantic is now fixed in backend
> CrawlExecution sortable on startTime

- src/modules/config/components/politenessconfig/politenessconfig-details-multi/politenessconfig-details-multi.component.html
- src/modules/config/components/politenessconfig/politenessconfig-details-multi/politenessconfig-details-multi.component.ts
- src/modules/config/components/politenessconfig/politenessconfig-details/politenessconfig-details.component.html
> Change default language in politeness view to english

- src/modules/app/app.module.ts
- src/modules/app/components/app/app.component.html
- src/modules/app/components/app/app.component.ts
- src/modules/app/components/crawlerstatus-dialog/crawlerstatus-dialog.component.html
- src/modules/app/components/crawlerstatus-dialog/crawlerstatus-dialog.component.spec.ts
- src/modules/app/components/crawlerstatus-dialog/crawlerstatus-dialog.component.ts
- src/modules/app/components/crawlerstatus/crawlerstatus.component.html
- src/modules/app/components/crawlerstatus/crawlerstatus.component.spec.ts
- src/modules/app/components/crawlerstatus/crawlerstatus.component.ts
- src/modules/app/components/index.ts
- src/modules/core/services/api/controller-api.service.ts
Add support to pause/unpause crawler
> Show crawler status in dashboard

- src/modules/app/components/app/app.component.ts
- src/modules/app/routing/app-routing.module.ts
- src/modules/core/services/auth/auth.service.ts
- src/modules/core/services/auth/guard.service.ts
- src/modules/report/services/crawl-log.service.ts
- fix crawllog page offset calculation
> Fix redirect to requested path after login

- src/main.ts
- src/modules/core/services/app.initializer.service.ts
> Enable easy overide of app configuration

- src/modules/report/components/crawl-execution-status-list/crawl-execution-status-list.component.html
- src/modules/report/components/crawl-execution-status-list/crawl-execution-status-list.component.ts
- src/modules/report/components/crawl-execution/crawl-execution.component.html
- src/modules/report/components/crawl-execution/crawl-execution.component.ts
- src/modules/report/components/job-execution/job-execution.component.html
- src/modules/report/services/crawl-execution.service.ts
> JobExecutionId filter in CrawlExecution report view. 

- src/modules/config/components/collection/collection-details/collection-details.component.html
- src/modules/config/components/collection/collection-details/collection-details.component.ts
- src/modules/config/components/collection/collection-dialog/collection-dialog.component.html
- Show error if missing file size
> Set default collection file size to 1GB

- angular.json
- package.json
- src/modules/commons/commons.module.ts
- src/modules/commons/directives/index.ts
- src/modules/commons/directives/prismjs.directive.ts
- src/modules/config/components/annotation/annotation.component.html
- src/modules/config/components/browserscript/browserscript-preview/browserscript-preview.component.html
- src/modules/config/components/browserscript/browserscript-preview/browserscript-preview.component.ts
- src/modules/config/components/collection/collection-preview/collection-preview.component.html
- src/modules/config/components/crawlconfig/crawlconfig-preview/crawlconfig-preview.component.html
- src/modules/config/components/crawljobs/crawljob-preview/crawljob-preview.component.html
- src/modules/config/components/entity/entity-view/entity-view.component.html
- src/modules/config/components/meta/meta-preview/meta-preview.component.css
- src/modules/config/components/meta/meta-preview/meta-preview.component.html
- src/modules/config/components/preview/preview.component.css
- src/modules/config/components/preview/preview.component.html
- src/modules/config/components/run-crawl-dialog/run-crawl-dialog.component.ts
- src/modules/config/configurations.module.ts
- src/modules/config/containers/configurations/configurations.component.ts
- src/modules/core/services/api/controller-api.service.ts
- src/modules/core/services/api/report-api.service.ts
- src/modules/report/containers/job-execution-detail/job-execution-detail.component.ts
- yarn.lock
- Highlight browserScript preview
> Remove execute db query

- src/modules/config/containers/configurations/configurations.component.ts
This reverts commit 01514eb699027d55bfb2b715f7737c44dcf5927d.
> Revert "Sort configurations list by name ascending as default"

- src/modules/report/components/crawl-execution-preview/crawl-execution-preview.component.html
- src/modules/report/components/crawl-execution-preview/crawl-execution-preview.component.ts
- src/modules/report/components/job-execution-preview/job-execution-preview.component.html
- src/modules/report/components/job-execution-preview/job-execution-preview.component.ts
- Change legend label font color based on theme
- Hide labels with no data
- Use specific colors for the different labels
> Style report preview charts
